### PR TITLE
Nest Script Rewrite

### PR DESCRIPTION
**Pull request by ccev**
I completely revamped this script.

## summary of changes:
- runtime improvements (about 1/4 the runtime for me)
- better area support (no extra multipolygon areas, geofences instead of bboxes, no extra config files)
- discord output now works with a bot which edits an existing nest message. it also has static map support. static maps show nests by showing X amounts of the sprite on its nest. where X = hourly average (only works with flos tileserver)
- less reliability on local files
- cleaning up code, logs and configs
- has PR26 for better marker results
- fixes a bug where multipolygons could have had multiple nests displayed
- area data is sorted by nest_avg so most important nests are on the top

This PR has been tested by a few users and should be ready for further testing. If you're interested 
in testing, I recommend cloning my fork `https://github.com/ccev/PMSFnestScript` in another directory. Please comment this PR or write a Discord message in the PMSF Discord server for feedback/issues/whatever. Thank You!

## things i might add:
- support for webhooks like the old script
- a migration script (current nest script to my fork)

### CODE REVIEW

**Comment by Zyahko** [comment]
Did a git clone into a separate folder and I believe I got it configured but I keep getting this error when I try to run `python3 nests.py` 

`Traceback (most recent call last):
  File "nests.py", line 4, in <module>
    import discord
  File "/home/swks/.local/lib/python3.6/site-packages/discord/__init__.py", line 25, in <module>
    from .client import Client
  File "/home/swks/.local/lib/python3.6/site-packages/discord/client.py", line 33, in <module>
    import aiohttp
  File "/home/swks/.local/lib/python3.6/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import BaseConnector as BaseConnector
  File "/home/swks/.local/lib/python3.6/site-packages/aiohttp/client.py", line 30, in <module>
    from yarl import URL
  File "/home/swks/.local/lib/python3.6/site-packages/yarl/__init__.py", line 1, in <module>
    from ._url import URL, cache_clear, cache_configure, cache_info
  File "/home/swks/.local/lib/python3.6/site-packages/yarl/_url.py", line 58, in <module>
    @rewrite_module
  File "/home/swks/.local/lib/python3.6/site-packages/yarl/_url.py", line 131, in URL
    _QUOTER = _Quoter(requote=False)
  File "yarl/_quoting.pyx", line 192, in yarl._quoting._Quoter.__init__
TypeError: __init__() got an unexpected keyword argument 'requote'`

**Comment by ccev** [comment]
@Zyahko Google says you need to `pip install -U yarl`. i wonder why it didn't do that when installing requirements

**Comment by Zyahko** [comment]
@ccev Yea that is odd. I ran the `pip3 install -r requirements.txt --upgrade` command like 3 different times because I wanted to make sure I installed the requirements. It works now though. Thanks.

**Comment by Zyahko** [comment]
Now getting this error when the script gets ready to send the nest messages.

`Saved Geojson file
Logging into Discord
Connected to Discord. Generating Nest messages and sending them.
Comparing your bot's emotes to needed nesting mons.
400 Bad Request (error code: 50035): Invalid Form Body
In embed.image.url: Not a well formed URL.
Traceback (most recent call last):
  File "nests.py", line 152, in on_ready
    await channel.send(embed=embed)
  File "/home/swks/nest-script/nest-venv/lib/python3.6/site-packages/discord/abc.py", line 905, in send
    nonce=nonce, allowed_mentions=allowed_mentions)
  File "/home/swks/nest-script/nest-venv/lib/python3.6/site-packages/discord/http.py", line 245, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.image.url: Not a well formed URL.
All done.
`

**Comment by nileplumb** [comment]
area_data csv customisation is deleted if there is not enough scan data to identify the customised nest

**Comment by jepke** [comment]
some sort of overpass cooldown would be nice to prevent it from crashing because of rate limiting when using 40 areas with a few humongous areas

**Comment by jepke** [comment]
I'm missing an option to disable empty the nest table.

**Comment by ccev** [comment]
> I'm missing an option to disable empty the nest table.

there's no need for this anymore. The only reason for madao's version to have that, were those multiple runs with different configs and only the first run had to empty the table.

**Comment by jepke** [comment]
Well in PMSF we still use manual nest submissions those get removed as well now.

**Pull request merged**
