### PR TITLE
Added middleman tileserver compatibility

### PR DESCRIPTION
**Pull request by Lecnets**
Added tile server compatibility using middleman

### CODE REVIEW

**Comment by ccev** [comment]
looks good to me. did anyone test this?

**Comment by ccev** [comment]
If there's a single confirmation of this PR being functional, I'm happy to merge 👀

**Comment by BadWolf0081** [comment]
> If there's a single confirmation of this PR being functional, I'm happy to merge 👀

I can confirm these changes make it work with middleman hiding our tileserver.  Also compatible with PR70.

**Comment by ccev** [comment]
cool

**Pull request merged**
