### PR TITLE
Correct center point algorithm for concave polygons

### LINKED ISSUE #25: Nest center should be inside the polygon even if it is concave
Possible solution: https://blog.mapbox.com/a-new-algorithm-for-finding-a-visual-center-of-a-polygon-7c77e6492fbc

Related discussions: https://github.com/WatWowMap/MapJS/pull/206#issuecomment-697077872

### PR DESCRIPTION
**Pull request by Mygod**
Fix #25.

### CODE REVIEW

**Comment by TurtIeSocks** [comment]
Much slower than master but works well. Nest icons are much more accurate now.

**Comment by Mygod** [comment]
Hmm there is probably some optimizations to be done here as it looks like a lot of the areas are actually filtered out. After all this looks like a worst case `O(1/eps^2)` algorithm.

For future improvements: From the tests, while it is certainly better than simply taking the centroid of the convex hull, it looks like this algorithm might not be perfectly ideal as the center of the largest inscribed circle in the polygon does not always align with what is perceived as the "visual center." Perhaps one way to fix it is to penalize points that are too far away from the centroid of the polygon. A possible alternative algorithm: https://stackoverflow.com/a/39408054/2245107

**Comment by Mygod** [comment]
Another issue with this algorithm is that it is sensitive to the choice of basis. For example, one degree in WE direction is usually much shorter than one degree in NS direction (think of the extreme example of being at the north/south pole). This results in the algorithm trying to fit a long oval (in NS direction) into the polygon instead of a circle, which makes it perform a bit even worse.

**Comment by ccev** [comment]
This has been implemented in v2 (nestwatcher)

**Pull request closed without merging**
