### PR TITLE
Separate pregen url and whitespace / trailing spaces cleanup

### PR DESCRIPTION
**Pull request by jepke**

### CODE REVIEW

**Comment by ccev** [comment]
Can you elaborate on why you'd want a sperate pregen config option?

**Comment by jepke** [comment]
> Can you elaborate on why you'd want a sperate pregen config option?

https://discord.com/channels/446375528157544450/553215076786503725/796532764609871933

**Comment by jepke** [comment]
Can this be merged or fixed in another way when using a tile server behind cloudflare.

**Comment by ccev** [comment]
No. I don't like how this is implemented here, since it would break every staticmap when people pull.

Since I still fail to understand the point of it, I'm also unable to implement it myself.

Have you considered using my tileserver-middleman? I could add support for that if that'd be a solution for your problem.

**Comment by jepke** [comment]
Issue is fairly simple... Nestwatcher requests a static map but on bigger maps it takes to long and cloudflare cuts off the connection resulting in no staticmap being generated.

No i cannot use shortcuts or internal routing to have nestwatcher bypass cloudflare that would degrade security.

I don't see why it would break as im using it for almost 2 months and works as its suppose to

**Comment by ccev** [comment]
Because you're adding a new config option that is then required when generating static maps. when people would then pull without adjusting the config, it'd break.

Did you take a look at tileserver-middleman?

**Comment by jepke** [comment]
Yes i looked at your tileserver-middleman but it's going to have the same issue.

**Comment by jepke** [comment]
> Because you're adding a new config option that is then required when generating static maps. when people would then pull without adjusting the config, it'd break.
> 
> Did you take a look at tileserver-middleman?

https://github.com/M4d40/nestwatcher/pull/51/commits/ca00175ab0de50d742a34155262b50547b895df2 now it wont break anymore happy?

**Pull request closed without merging**
